version: "3"

services:
  target:
    image: ubuntu:latest
    container_name: target
    command: tail -f /dev/null
    networks:
      test_net:
        ipv4_address: 172.18.0.2

  attacker:
    image: rust:latest
    container_name: attacker
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      test_net:
        ipv4_address: 172.18.0.3
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
